schema_version = "1.0.0"

id = "treeGen"
version = "1.0.0"
name = "treeGen"
tagline = "Generate a parametric tree"
maintainer = "Jens Maier"
type = "add-on"
location = "View3d > Sidebar"

website = "https://github.com/Jens-Maier/tree"
support = "COMMUNITY"
tags = ["Add Mesh", ]

blender_version_min = "4.5.3"

license = [
  "SPDX:GPL-3.0-or-later",
]
copyright = [
  "2025 Jens Maier",
]

[permissions]
files = "Read/write json files from/to disk"