schema_version = "1.0.0"

id = "treeGen"
version = "1.0.3"
name = "treeGen" # has to be exactly the same name as the folder that contains __init__.py, ...py, blender_manifest.toml
tagline = "Procedural tree generator"
maintainer = "Jens Maier"
type = "add-on"
location = "View3d > Sidebar"

support = "COMMUNITY"
tags = ["Add Mesh", ]

blender_version_min = "4.5.3"

license = [
  "SPDX:GPL-3.0-or-later",
]
copyright = [
  "2025 Jens Maier",
]

[permissions]
files = "Read/write json files from/to disk"